paths:
  dataset_root: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_data
  experiment_log_dir: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_logs/seismic_facies_phase1
  bpe_path: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
  init_checkpoint: C:/Users/umair_tariq/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
seismic_train:
  category_name: seismic facies
  train_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomHorizontalFlip
      consistent_transform: true
      p: 0.5
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes:
        _target_: sam3.train.transforms.basic.get_random_resize_scales
        size: 1008
        min_size: 480
        rounded: false
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: 1008
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
      size: 1008
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
      query_filter:
        _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean:
      - 0.5
      - 0.5
      - 0.5
      std:
      - 0.5
      - 0.5
      - 0.5
  val_transforms:
  - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
    transforms:
    - _target_: sam3.train.transforms.segmentation.DecodeRle
    - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
      sizes: 1008
      max_size:
        _target_: sam3.train.transforms.basic.get_random_resize_max_size
        size: 1008
      square: true
      consistent_transform: false
    - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
    - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
      mean:
      - 0.5
      - 0.5
      - 0.5
      std:
      - 0.5
      - 0.5
      - 0.5
  loss:
    _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
    matcher:
      _target_: sam3.train.matcher.BinaryHungarianMatcherV2
      focal: true
      cost_class: 2.0
      cost_bbox: 5.0
      cost_giou: 2.0
      alpha: 0.25
      gamma: 2
      stable: false
    o2m_weight: 2.0
    o2m_matcher:
      _target_: sam3.train.matcher.BinaryOneToManyMatcher
      alpha: 0.3
      threshold: 0.4
      topk: 4
    use_o2m_matcher_on_o2m_aux: false
    loss_fns_find:
    - _target_: sam3.train.loss.loss_fns.Boxes
      weight_dict:
        loss_bbox: 5.0
        loss_giou: 2.0
    - _target_: sam3.train.loss.loss_fns.IABCEMdetr
      weak_loss: false
      weight_dict:
        loss_ce: 5.0
        presence_loss: 5.0
      pos_weight: 10.0
      alpha: 0.25
      gamma: 2
      use_presence: true
      pos_focal: false
      pad_n_queries: 200
      pad_scale_pos: 1.0
    - _target_: sam3.train.loss.loss_fns.Masks
      focal_alpha: 0.25
      focal_gamma: 2.0
      weight_dict:
        loss_mask: 20.0
        loss_dice: 10.0
      compute_aux: false
    loss_fn_semantic_seg: null
    scale_by_find_batch_size: true
scratch:
  enable_segmentation: true
  d_model: 256
  pos_embed:
    _target_: sam3.model.position_encoding.PositionEmbeddingSine
    num_pos_feats: 256
    normalize: true
    scale: null
    temperature: 10000
  use_presence_eval: true
  original_box_postprocessor:
    _target_: sam3.eval.postprocessors.PostProcessImage
    max_dets_per_img: -1
    use_original_ids: true
    use_original_sizes_box: true
  use_presence: true
  matcher:
    _target_: sam3.train.matcher.BinaryHungarianMatcherV2
    focal: true
    cost_class: 2.0
    cost_bbox: 5.0
    cost_giou: 2.0
    alpha: 0.25
    gamma: 2
    stable: false
  scale_by_find_batch_size: true
  resolution: 1008
  consistent_transform: false
  max_ann_per_img: 20
  train_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  train_norm_std:
  - 0.5
  - 0.5
  - 0.5
  val_norm_mean:
  - 0.5
  - 0.5
  - 0.5
  val_norm_std:
  - 0.5
  - 0.5
  - 0.5
  num_train_workers: 8
  num_val_workers: 0
  max_data_epochs: 2
  target_epoch_size: 1500
  hybrid_repeats: 1
  context_length: 2
  gather_pred_via_filesys: false
  lr_scale: 1.0
  lr_transformer: 0.0002
  lr_vision_backbone: 0.0
  lr_language_backbone: 0.0
  lrd_vision_backbone: 0.9
  wd: 0.1
  scheduler_timescale: 15
  scheduler_warmup: 5
  scheduler_cooldown: 15
  val_batch_size: 1
  collate_fn_val:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: 1
    dict_key: seismic_facies
    with_seg_masks: true
  gradient_accumulation_steps: 1
  train_batch_size: 1
  collate_fn:
    _target_: sam3.train.data.collator.collate_fn_api
    _partial_: true
    repeats: 1
    dict_key: all
    with_seg_masks: true
trainer:
  _target_: sam3.train.trainer.Trainer
  skip_saving_ckpts: false
  empty_gpu_mem_cache_after_eval: true
  skip_first_val: false
  max_epochs: 2
  accelerator: cuda
  seed_value: 123
  val_epoch_freq: 1
  mode: train
  gradient_accumulation_steps: 1
  distributed:
    backend: gloo
    find_unused_parameters: true
    gradient_as_bucket_view: true
    static_graph: true
  loss:
    all:
      _target_: sam3.train.loss.sam3_loss.Sam3LossWrapper
      matcher:
        _target_: sam3.train.matcher.BinaryHungarianMatcherV2
        focal: true
        cost_class: 2.0
        cost_bbox: 5.0
        cost_giou: 2.0
        alpha: 0.25
        gamma: 2
        stable: false
      o2m_weight: 2.0
      o2m_matcher:
        _target_: sam3.train.matcher.BinaryOneToManyMatcher
        alpha: 0.3
        threshold: 0.4
        topk: 4
      use_o2m_matcher_on_o2m_aux: false
      loss_fns_find:
      - _target_: sam3.train.loss.loss_fns.Boxes
        weight_dict:
          loss_bbox: 5.0
          loss_giou: 2.0
      - _target_: sam3.train.loss.loss_fns.IABCEMdetr
        weak_loss: false
        weight_dict:
          loss_ce: 5.0
          presence_loss: 5.0
        pos_weight: 10.0
        alpha: 0.25
        gamma: 2
        use_presence: true
        pos_focal: false
        pad_n_queries: 200
        pad_scale_pos: 1.0
      - _target_: sam3.train.loss.loss_fns.Masks
        focal_alpha: 0.25
        focal_gamma: 2.0
        weight_dict:
          loss_mask: 20.0
          loss_dice: 10.0
        compute_aux: false
      loss_fn_semantic_seg: null
      scale_by_find_batch_size: true
    default:
      _target_: sam3.train.loss.sam3_loss.DummyLoss
  data:
    train:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        load_segmentation: true
        transforms:
        - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
          transforms:
          - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
            query_filter:
              _target_: sam3.train.transforms.filter_query_transforms.FilterCrowds
          - _target_: sam3.train.transforms.segmentation.DecodeRle
          - _target_: sam3.train.transforms.basic_for_api.RandomHorizontalFlip
            consistent_transform: true
            p: 0.5
          - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
            sizes:
              _target_: sam3.train.transforms.basic.get_random_resize_scales
              size: 1008
              min_size: 480
              rounded: false
            max_size:
              _target_: sam3.train.transforms.basic.get_random_resize_max_size
              size: 1008
            square: true
            consistent_transform: false
          - _target_: sam3.train.transforms.basic_for_api.PadToSizeAPI
            size: 1008
            consistent_transform: false
          - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
          - _target_: sam3.train.transforms.filter_query_transforms.FlexibleFilterFindGetQueries
            query_filter:
              _target_: sam3.train.transforms.filter_query_transforms.FilterEmptyTargets
          - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
            mean:
            - 0.5
            - 0.5
            - 0.5
            std:
            - 0.5
            - 0.5
            - 0.5
        max_ann_per_img: 20
        multiplier: 1
        max_train_queries: 100
        max_val_queries: 100
        training: true
        use_caching: false
        img_folder: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_data/images/train/
        ann_file: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_data/train.json
      shuffle: true
      batch_size: 1
      num_workers: 8
      pin_memory: true
      drop_last: true
      collate_fn:
        _target_: sam3.train.data.collator.collate_fn_api
        _partial_: true
        repeats: 1
        dict_key: all
        with_seg_masks: true
    val:
      _target_: sam3.train.data.torch_dataset.TorchDataset
      dataset:
        _target_: sam3.train.data.sam3_image_dataset.Sam3ImageDataset
        load_segmentation: true
        coco_json_loader:
          _target_: sam3.train.data.coco_json_loaders.COCO_FROM_JSON
          include_negatives: true
          category_chunk_size: 1
          _partial_: true
        img_folder: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_data/images/val/
        ann_file: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_data/val.json
        transforms:
        - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
          transforms:
          - _target_: sam3.train.transforms.segmentation.DecodeRle
          - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
            sizes: 1008
            max_size:
              _target_: sam3.train.transforms.basic.get_random_resize_max_size
              size: 1008
            square: true
            consistent_transform: false
          - _target_: sam3.train.transforms.basic_for_api.ToTensorAPI
          - _target_: sam3.train.transforms.basic_for_api.NormalizeAPI
            mean:
            - 0.5
            - 0.5
            - 0.5
            std:
            - 0.5
            - 0.5
            - 0.5
        max_ann_per_img: 100
        multiplier: 1
        training: false
      shuffle: false
      batch_size: 1
      num_workers: 0
      pin_memory: true
      drop_last: false
      collate_fn:
        _target_: sam3.train.data.collator.collate_fn_api
        _partial_: true
        repeats: 1
        dict_key: seismic_facies
        with_seg_masks: true
  model:
    _target_: sam3.model_builder.build_sam3_image_model
    bpe_path: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/sam3/sam3/assets/bpe_simple_vocab_16e6.txt.gz
    device: cpu
    eval_mode: false
    enable_segmentation: true
    checkpoint_path: C:/Users/umair_tariq/.cache/huggingface/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt
    load_from_HF: false
  optim:
    amp:
      enabled: true
      amp_dtype: bfloat16
    optimizer:
      _target_: torch.optim.AdamW
    gradient_clip:
      _target_: sam3.train.optim.optimizer.GradientClipper
      max_norm: 0.1
      norm_type: 2
    param_group_modifiers:
    - _target_: sam3.train.optim.optimizer.layer_decay_param_modifier
      _partial_: true
      layer_decay_value: 0.9
      apply_to: backbone.vision_backbone.trunk
      overrides:
      - pattern: '*pos_embed*'
        value: 1.0
    options:
      lr:
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: 0.0002
          timescale: 15
          warmup_steps: 5
          cooldown_steps: 15
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: 0.0
          timescale: 15
          warmup_steps: 5
          cooldown_steps: 15
        param_names:
        - backbone.vision_backbone.*
      - scheduler:
          _target_: sam3.train.optim.schedulers.InverseSquareRootParamScheduler
          base_lr: 0.0
          timescale: 15
          warmup_steps: 5
          cooldown_steps: 15
        param_names:
        - backbone.language_backbone.*
      weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.1
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.0
        param_names:
        - '*bias*'
        module_cls_names:
        - torch.nn.LayerNorm
  checkpoint:
    save_dir: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_logs/seismic_facies_phase1/checkpoints
    save_freq: 5
    resume_from: null
  logging:
    tensorboard_writer:
      _target_: sam3.train.utils.logger.make_tensorboard_logger
      log_dir: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_logs/seismic_facies_phase1/tensorboard
      flush_secs: 120
      should_log: true
    wandb_writer: null
    log_dir: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_logs/seismic_facies_phase1/logs/seismic_facies_phase1
    log_freq: 10
launcher:
  num_nodes: 1
  gpus_per_node: 1
  experiment_log_dir: C:/Users/umair_tariq/Downloads/Downloads/seismic_prototype/finetune_logs/seismic_facies_phase1
  multiprocessing_context: forkserver
submitit:
  account: null
  partition: null
  qos: null
  timeout_hour: 72
  use_cluster: false
  cpus_per_task: 8
  port_range:
  - 10000
  - 65000
  constraint: null
